---
site_name: HTAN LinkML
site_description: HTAN LinkML Data Model
site_author: HTAN Consortium

theme:
  name: material

plugins:
  - search
  - mermaid2:
      arguments:
        theme: default
        themeVariables:
          primaryColor: '#ff0000'
          primaryTextColor: '#fff'
          primaryBorderColor: '#7C0000'
          lineColor: '#F8B229'
          secondaryColor: '#006100'
          tertiaryColor: '#fff'

nav:
  - Home: index.md
  - Modules:
    - Clinical:
      - Demographics: Demographics.md
      - Diagnosis: Diagnosis.md
      - Exposure: Exposure.md
      - Family History: FamilyHistory.md
      - Followup: FollowUp.md
      - Molecular Test: MolecularTest.md
      - Therapy: Therapy.md
      - Vital Status: VitalStatus.md
  - Quick Start: quickstart.md
  - Development: development.md