defaults:
  # Set default paths for input data and templates
  data_directory: "./data"
  template_directory: "./Templates"
  modules_directory: "./Modules"
  
validation:
  # Set options for validation (can be expanded based on your needs)
  check_required_fields: true
  check_unique_ids: true

metadata:
  # Global metadata that might apply across multiple templates or modules
  creator: "Aditi Gopalan"
  version: "1.0"
  license: "CC BY 4.0"
  description: "LinkML schema for HTAN2 Imaging Template"
  
paths:
  # Example of paths for specific file locations
  collection_information_path: "./Worksheets/CollectionInformation.yaml"
  participant_information_path: "./Worksheets/ParticipantInformation.yaml"
  file_specific_general_information_path: "./Worksheets/FileSpecificGeneralInformation.yaml"
