name: Build and Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry.
        run: pipx install poetry

      - name: Install dependencies.
        run: poetry install -E docs

      - name: Build documentation.
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          # Run the Python script to generate documentation
          poetry run python generate_docs.py
          # Copy about.md if it doesn't exist
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          
          # Commit the generated files
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "docs: update generated documentation" || true
          
          # Build the documentation using Poetry
          poetry run mkdocs build

  deploy-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry.
        run: pipx install poetry

      - name: Install dependencies.
        run: poetry install -E docs

      - name: Deploy to GitHub Pages
        run: poetry run mkdocs gh-deploy --force

  preview-docs:
    if: github.event_name == 'pull_request'
    needs: build-docs
    runs-on: ubuntu-latest

    steps:
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/
          preview-branch: gh-pages